# Generated by Django 3.1.6 on 2021-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=10)),
                ('Customer_Detail', models.CharField(max_length=100)),
                ('Mail_ID', models.EmailField(max_length=254)),
                ('Service_ID', models.IntegerField()),
                ('Service_Type', models.CharField(max_length=20)),
                ('Problem_Description', models.TextField(max_length=200)),
            ],
        ),
    ]
